# Pre-commit hooks configuration for Python cron job project

repos:
  # Core Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace          # Remove trailing whitespace
      - id: end-of-file-fixer            # Ensure files end with newline
      - id: check-yaml                   # Validate YAML files
      - id: check-added-large-files      # Prevent committing large files

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  # isort for import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: Sort Python imports

  # Flake8 for linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  # MyPy type-checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  # Safety check for Python dependencies
  - repo: https://github.com/pyupio/safety
    rev: v2.3.0
    hooks:
      - id: safety
        args: ["check"]
